### ISSUE TITLE
Error: Profile ID MyProfileId not found

### ISSUE THREAD

**Issue by kkpsiren** [dabit3/lens-gated-publications#2]
When trying to gate either with NFT or with ERC20,  I get this error msg with my profileId in it.
```
index.umd.js?f60d:1 Uncaught (in promise) Error: Profile ID <MyProfileId> not found.
    at t [as constructor] (index.umd.js?f60d:1:12187)
    at new t (index.umd.js?f60d:1:13563)
    at e.eval (index.umd.js?f60d:1:795052)
    at eval (index.umd.js?f60d:1:11841)
    at Object.eval [as next] (index.umd.js?f60d:1:11950)
    at s (index.umd.js?f60d:1:10664)
```

**Comment by kkpsiren** [comment]
Solved. App seems to work great on mainnet but failed with testnet.

**Comment by Azleal** [comment]
<img width="552" alt="image" src="https://github.com/dabit3/lens-gated-publications/assets/7901126/3aa1e9d9-c647-4f71-9d51-551c0b4e6222">

**it's sitll happending. I have both testnet and mainnet lens handler. i choosed polygon and erc20 token is usdc. when i clicked submit, error shown as below**  @kkpsiren please help, thanks

<img width="535" alt="image" src="https://github.com/dabit3/lens-gated-publications/assets/7901126/64df9585-6caa-4d9a-8f45-7b1c288a97cf">
